name: goql
reportingTeam: fnd-dtss
description: A GraphQL client package written in Go.
slack: dev-tooling-notifications
library: true
releaseType: semver
deployTo:
  environments: []
arguments:
  dependencies:
    optional: []
    required: []
  description: A GraphQL client package written in Go.
  opslevel:
    confluenceSpaceKey: ""
    designDocumentLink: ""
  reportingTeam: fnd-dtss
  type: []
modules:
  - url: https://github.com/getoutreach/stencil-base
    version: george-e-shaw-iv/feat/add-templates
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: ""
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
