name: goql
reportingTeam: fnd-dtss
description: ""
slack: ""
library: true
releaseType: semver
deployTo:
  environments: []
arguments:
  dependencies:
    optional: []
    required: []
  description: ""
  reportingTeam: fnd-dtss
  type: []
modules:
  - url: https://github.com/getoutreach/stencil-base
    version: ""
