name: goql
reportingTeam: end-ades
description: A GraphQL client package written in Go.
oss: true
slack: orexservice-notifications
library: true
circleAPIKey: ""
lintroller: bronze
tracing: honeycomb
metrics: datadog
releaseType: semver
deployTo:
  environments: []
arguments:
  circleAPIKey: ""
  commands: []
  commitGuard: false
  dependencies:
    optional: []
    required: []
  description: A GraphQL client package written in Go.
  grpcClients: []
  kubernetes:
    groups: []
  lintroller: bronze
  metrics: datadog
  opslevel:
    confluenceSpaceKey: ""
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: true
  releaseOptions:
    allowMajorVersions: null
    enablePrereleases: false
  reportingTeam: end-ades
  resources: {}
  service: false
  tracing: honeycomb
  tutorial: false
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-outreach
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-actions
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
  - name: github.com/getoutreach/stencil-opslevel
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: ""
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
