name: goql
reportingTeam: fnd-dtss
description: A GraphQL client package written in Go.
oss: true
slack: dev-tooling-notifications
library: true
circleAPIKey: ""
releaseType: semver
deployTo:
  environments: []
arguments:
  circleAPIKey: ""
  commands: []
  dependencies:
    optional: []
    required: []
  description: A GraphQL client package written in Go.
  grpcClients: []
  opslevel:
    confluenceSpaceKey: ""
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: true
  releaseOptions:
    allowMajorVersions: null
    allowPrereleases: false
  reportingTeam: fnd-dtss
  type:
    - library
modules:
  - name: github.com/getoutreach/stencil-base
    version: ""
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: ""
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
