name: goql
reportingTeam: fnd-dtss
description: A GraphQL client package written in Go.
slack: dev-tooling-notifications
library: true
oss: true
circleAPIKey: ""
releaseType: semver
deployTo:
  environments: []
arguments:
  circleAPIKey: ""
  dependencies:
    optional: []
    required: []
  description: A GraphQL client package written in Go.
  opslevel:
    confluenceSpaceKey: ""
    designDocumentLink: ""
  oss: true
  reportingTeam: fnd-dtss
  type:
    - library
modules:
  - url: https://github.com/getoutreach/stencil-base
    version: ""
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: ""
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
