version: 2.1

orbs:
  shared: getoutreach/shared@1.30.6

# DEPRECATED: Use the devbase orb instead:
# https://github.com/getoutreach/devbase/tree/main/orbs/shared
commands:
  with_job_span:
    parameters:
      steps:
        type: steps
    steps:
      - run:
          name: DEPRECATION NOTICE
          command: echo "with_job_span is deprecated and should be removed"
      - steps: << parameters.steps >>

jobs:
  ###Block(circleJobs)
  ###EndBlock(circleJobs)

  test:
    executor:
      name: shared/testbed-docker
      go_version: 1.17.1
    docker:
      - image: gcr.io/outreach-docker/bootstrap/testbed:1.17.1
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_ACCOUNT
    environment:
      ###Block(testEnvVars)
      ###EndBlock(testEnvVars)
    steps:
      - shared/setup_environment:
          setup_remote_docker: true
      - run:
          name: Wait for Infrastructure to be Ready
          command: ./scripts/shell-wrapper.sh ci/testing/wait-for-infra.sh
      - shared/with_go_cache
      - run:
          name: Run unit tests
          # Store the results of our tests in the $TEST_RESULTS directory
          command: make test | tee ${TEST_RESULTS}/go-test.out
      - run:
          name: Upload Code Coverage
          command: ./scripts/shell-wrapper.sh ci/testing/coveralls.sh
      - shared/save_go_cache # We save at the end because binaries are included with this
      - shared/upload_test_results

  release-dryrun:
    executor:
      name: shared/testbed-docker
      go_version: 1.17.1
    steps:
      - shared/setup_environment:
          setup_remote_docker: true
      - shared/with_node_cache:
          save: true
      - run:
          name: Release (Dry-run)
          command: ./scripts/shell-wrapper.sh ci/release/dryrun.sh
  release:
    executor:
      name: shared/testbed-docker
      go_version: 1.17.1
    steps:
      - shared/setup_environment:
          setup_remote_docker: true
      - shared/with_node_cache:
          save: true
      - run:
          name: Release
          command: GH_TOKEN=$OUTREACH_GITHUB_TOKEN yarn --frozen-lockfile semantic-release

  trigger_documentation:
    executor:
      name: shared/testbed-docker
      go_version: 1.17.1
    steps:
      - shared/setup_environment
      - shared/with_go_cache
      - run:
          name: Trigger Documentation Update
          command: ./scripts/shell-wrapper.sh ci/release/docs.sh

workflows:
  version: 2
  ###Block(circleWorkflows)
  ###EndBlock(circleWorkflows)
  build_and_test:
    jobs:
      ###Block(circleWorkflowJobs)
      ###EndBlock(circleWorkflowJobs)
      - release:
          context:
            - docker-registry
            - npm-credentials
          requires:
            - test
          ###Block(circleReleaseRequires)
          ###EndBlock(circleReleaseRequires)
          filters:
            branches:
              only:
                - master
                - main
      - release-dryrun:
          context:
            - docker-registry
            - npm-credentials
          filters:
            branches:
              ignore:
                - master
                - main
      - test:
          context:
            - docker-registry
            - npm-credentials
      - trigger_documentation:
          context:
            - docker-registry
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
